[package]
name = "music-overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
gtk4 = "0.7.3"
reqwest = { version = "0.11.21", features = ["blocking"] }
